sonar.projectKey=ahKafagy02_tp1_devops
sonar.organization=ahkafagy02
sonar.host.url=https://sonarcloud.io
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
sonar.java.coveragePlugin=jacoco
